@members_api_HostAddress = http://localhost:5288
@leave_api_HostAddress = http://localhost:5142

GET {{members_api_HostAddress}}/members
Accept: application/json

###

GET {{members_api_HostAddress}}/health
Accept: application/json

###

POST {{members_api_HostAddress}}/members
Content-Type: application/json

{
    "firstName": "{{$random.name.firstName}}",
    "lastName": "{{$random.name.lastName}}",
    "email": "{{$random.email}}",
    "DateOfBirth": "2022-07-26T00:00:00"
}

###

GET {{leave_api_HostAddress}}/Leaves/users/0194f811-7f34-7ae7-8bb0-d72922d7b7e2
Content-Type: application/json

###

GET {{leave_api_HostAddress}}/Leaves
Accept: application/json

###

POST {{leave_api_HostAddress}}/Leaves
Content-Type: application/json

{
    "reason": "{{$random.name.firstName}}",
    "leaveType": "Annual",
    "memberId": "0194f811-7f34-7ae7-8bb0-d72922d7b7e2",
    "startDate": "2022-07-26T00:00:00",
    "endDate": "2022-07-28T00:00:00"
}
